#!/usr/bin/env fish

pushd ~/Repos/pleo/pleo/ops/chargebacks/

python replay_chargeback.py \
        --user=Pagobox \
        --password=(pass pleoprod/GPS_PASSWORD) \
        --client-id=(pass pleoprod/HYDRA_CLIENT_ID) \
        --client-secret=(pass pleoprod/HYDRA_CLIENT_SECRET)

popd
